### ISSUE TITLE
BUG DAMAGE AREA

### ISSUE THREAD

**Issue by Finmichiakii** [chiteroman/ToramHack#1]
sorry chiteroman i have issues When I have activated the AOE damage cheat to the number I have determined, why does my Toram get stuck and freeze?

**Comment by chiteroman** [comment]
Can you send a video? Maybe ASSobimo patched it 😢

**Comment by Finmichiakii** [comment]
now it's not because I put in too many numbers😅
thank you for your hard work

**Comment by 00JanJan00** [comment]
@chiteroman have u ever faced any banned ?

**Comment by chiteroman** [comment]
> @chiteroman have u ever faced any banned issues ?

Nope
